### ISSUE TITLE
can not build successful on windows 11 python 3.10.11 cython 3.0.0.b3

### ISSUE THREAD

**Issue by zhusihan-python** [kleisauke/cyvips#1]
hello sir, im interested in making libvips binding in Cython, but i don't have the knowledge to achieve that now

this project is awesome, is it still in maintainance

i build it get error like this
```
src\__init__.pyx:32:14: Cannot assign type 'void (void) except * nogil' to 'void (*)(void) noexcept nogil'
Traceback (most recent call last):
  File "F:\projects\cyvips\setup.py", line 79, in <module>
    ext_modules=cythonize(ext_modules,
  File "D:\softwares\py3109\lib\site-packages\Cython\Build\Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "D:\softwares\py3109\lib\site-packages\Cython\Build\Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/cyvips.pyx
```

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/kleisauke/cyvips#conclusion ?

**Comment by zhusihan-python** [comment]
thank you for relpy, kleis
it means that its meaningless to write the python bingings in cython from the performance perspective right.

i'm learning cython by solve some tiny [math problems](https://github.com/zhusihan-python/cybase). 
when i try to find a bigger problem or project, your project is an awesome example how to write a cython project, another one i found is uvloop. i just want to improve my cython skills by mock your program.

i wonder how you achieve the high level skills of cython, should i learn some c before i dive deeper in cython.
any advise would be appreciate!

**Comment by kleisauke** [comment]
Commit f40c3d5126bc07a80e8e239049957c80837cd02d should fix this.

I think(?) knowledge of C/C++ is not necessary, since Cython only transpiles Python-like syntax to C.
